# Generated by Django 3.1.4 on 2020-12-30 04:54

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('iptv_filter', '0001_initial'), ('iptv_filter', '0002_auto_20201228_1831'), ('iptv_filter', '0003_auto_20201228_1857'), ('iptv_filter', '0004_auto_20201228_2041'), ('iptv_filter', '0005_auto_20201228_2053'), ('iptv_filter', '0006_auto_20201228_2126'), ('iptv_filter', '0007_auto_20201228_2133'), ('iptv_filter', '0008_auto_20201229_0422'), ('iptv_filter', '0009_auto_20201230_0014'), ('iptv_filter', '0010_auto_20201230_0016'), ('iptv_filter', '0011_auto_20201230_0019'), ('iptv_filter', '0012_auto_20201230_0022')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField(max_length=100)),
                ('last_updated', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='CachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.TextField(max_length=5)),
                ('file', models.BinaryField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=50)),
                ('included', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvg_id', models.CharField(max_length=50)),
                ('tvg_name', models.CharField(max_length=100)),
                ('tvg_logo', models.TextField()),
                ('stream_url', models.URLField()),
                ('included', models.BooleanField(default=None, null=True)),
                ('playlist_group', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iptv_filter.playlistgroup')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EpgChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('icon', models.TextField(null=True)),
                ('playlist_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iptv_filter.playlistchannel')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EpgProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=20)),
                ('stop', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField(blank=True)),
                ('epg_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptv_filter.epgchannel')),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
