# Generated by Django 3.1.4 on 2020-12-28 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50)),
                ('value', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CachedFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_type', models.TextField(max_length=5)),
                ('file', models.BinaryField()),
            ],
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('icon', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='FilterConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tvg_id', models.CharField(max_length=50)),
                ('tvg_name', models.CharField(max_length=100)),
                ('tvg_logo', models.URLField()),
                ('stream_url', models.URLField()),
                ('group_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Programme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('included', models.BooleanField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptv_filter.channel')),
            ],
        ),
    ]
