# Generated by Django 3.1.4 on 2020-12-31 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_filter', '0001_squashed_0006_auto_20201230_2044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistchannel',
            name='group_title',
            field=models.CharField(max_length=50),
        ),
    ]
