# Generated by Django 3.1.4 on 2020-12-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_filter', '0001_squashed_0012_auto_20201230_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appconfig',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='cachedfile',
            name='last_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='epgchannel',
            name='last_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='epgprogramme',
            name='last_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlistchannel',
            name='included',
            field=models.BooleanField(db_index=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='playlistchannel',
            name='last_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='playlistchannel',
            name='playlist_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptv_filter.playlistgroup'),
        ),
        migrations.AlterField(
            model_name='playlistgroup',
            name='included',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='playlistgroup',
            name='last_updated',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
