# Generated by Django 3.1.4 on 2020-12-28 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_filter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistchannel',
            name='included',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='programme',
            name='included',
            field=models.BooleanField(default=False),
        ),
    ]
