# Generated by Django 3.1.4 on 2020-12-28 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_filter', '0002_auto_20201228_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaylistGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_title', models.CharField(max_length=50)),
                ('included', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlistchannel',
            name='group_title',
        ),
        migrations.AddField(
            model_name='playlistchannel',
            name='playlist_group',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='iptv_filter.playlistgroup'),
            preserve_default=False,
        ),
    ]
