# Generated by Django 3.1.5 on 2021-02-07 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_filter', '0002_auto_20201230_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlistchannel',
            name='first_seen',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
