# Generated by Django 3.1.4 on 2020-12-28 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_filter', '0003_auto_20201228_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='EpgChannel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50)),
                ('display_name', models.CharField(max_length=50)),
                ('icon', models.URLField()),
                ('playlist_channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='iptv_filter.playlistchannel')),
            ],
        ),
        migrations.CreateModel(
            name='EpgProgramme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=20)),
                ('end', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
                ('epg_channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iptv_filter.epgchannel')),
            ],
        ),
        migrations.DeleteModel(
            name='FilterConfig',
        ),
        migrations.RemoveField(
            model_name='programme',
            name='channel',
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.DeleteModel(
            name='Programme',
        ),
    ]
