# Generated by Django 3.1.4 on 2020-12-28 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_filter', '0006_auto_20201228_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistchannel',
            name='included',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
