# Generated by Django 3.1.4 on 2020-12-29 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iptv_filter', '0007_auto_20201228_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlistchannel',
            name='tvg_logo',
            field=models.TextField(),
        ),
    ]
